database: app/db/**/*
component: app/src/components/**/*

resources:
- any: ['resources/**/*']
  all: ['!resources/lang/*']
language: resources/lang/*

backend: app/electron/**/*
frontend:
- any: ['app/src/**/*.html', 'app/src/**/*.css']

critical:
    - '(critical|urgent)'